Repository maxime-groff/zoneson-clone, pull requests merged in 2020-10, with the labels that each got.

#7 Feat/design
  package-lock.json
  public/index.html
  src/assets/css/main.scss
  src/components/PlaySound.vue
  src/views/Home.vue
  src/views/Tag.vue
Labels: design

#10 Feat/player button
  src/components/PlaySound.vue
  src/views/Tag.vue
Labels: feature

#11 feat: css v1
  src/assets/css/main.scss
  src/assets/css/partials/_global.scss
  src/components/Header.vue
  src/components/RandomColor.vue
  src/layouts/Default.vue
  src/router/index.js
  src/views/Home.vue
  src/views/Tag.vue
Labels: design

#12 Develop
  package-lock.json
  package.json
  public/audio/sound.mp3
  public/index.html
  src/App.vue
  src/assets/css/main.scss
  src/assets/css/partials/_global.scss
  src/components/Header.vue
  src/components/PlaySound.vue
  src/components/RandomColor.vue
  src/layouts/Default.vue
  src/main.js
  src/router/index.js
  src/views/Home.vue
  src/views/Tag.vue
  yarn.lock
Labels: deploy
